#!/bin/bash
set -e

# ============================================================================
# PgBouncer Entrypoint with Vault Integration
# ============================================================================

echo "=== Starting PgBouncer with Vault Integration ==="

# Configuration defaults
PGBOUNCER_CONFIG_DIR="${PGBOUNCER_CONFIG_DIR:-/etc/pgbouncer}"
PGBOUNCER_LOG_DIR="${PGBOUNCER_LOG_DIR:-/var/log/pgbouncer}"
PGBOUNCER_PORT="${PGBOUNCER_PORT:-6432}"

# Create necessary directories
mkdir -p "$PGBOUNCER_CONFIG_DIR" "$PGBOUNCER_LOG_DIR" /var/run/postgresql
chown -R postgres:postgres "$PGBOUNCER_LOG_DIR" || true
chown -R postgres:postgres /var/run/postgresql || true
chown postgres:postgres "$PGBOUNCER_CONFIG_DIR" 2>/dev/null || true
chmod 750 "$PGBOUNCER_CONFIG_DIR" 2>/dev/null || true
chmod 777 /var/run/postgresql 2>/dev/null || true

# ============================================================================
# SECTION 1: Vault Secrets Integration
# ============================================================================

echo "=== Fetching credentials from Vault ==="

# Set defaults from environment (fallback if Vault fails)
DB_ADMIN_USER="${DB_ADMIN_USER:-pgadmin}"
DB_ADMIN_PASSWORD="${DB_ADMIN_PASSWORD}"
DB_REPLICATION_USER="${DB_REPLICATION_USER:-replicator}"
DB_REPLICATION_PASSWORD="${DB_REPLICATION_PASSWORD}"

# Source vault helper if present
if [ -f /etc/vault/vault-secrets.sh ]; then
  source /etc/vault/vault-secrets.sh
elif [ -f /vault-secrets.sh ]; then
  source /vault-secrets.sh
fi

# If Vault Agent rendered file exists, load and export variables as env
if [ -f /etc/vault/secrets/postgres.env ]; then
  set -a
  source /etc/vault/secrets/postgres.env
  set +a
  echo "Loaded /etc/vault/secrets/postgres.env"
fi

# If POSTGRES_PASSWORD provided via rendered file, map to DB_ADMIN_PASSWORD
if [ -n "${POSTGRES_PASSWORD:-}" ] && [ -z "${DB_ADMIN_PASSWORD:-}" ]; then
  DB_ADMIN_PASSWORD="$POSTGRES_PASSWORD"
  export DB_ADMIN_PASSWORD
fi
if [ -n "${REPLICATION_PASSWORD:-}" ] && [ -z "${DB_REPLICATION_PASSWORD:-}" ]; then
  DB_REPLICATION_PASSWORD="$REPLICATION_PASSWORD"
  export DB_REPLICATION_PASSWORD
fi

if command -v verify_vault_connection >/dev/null 2>&1; then
  # Attempt AppRole login
  if [ -n "${VAULT_ROLE_ID:-}" ] && [ -n "${VAULT_SECRET_ID:-}" ]; then
    login_with_approle "$VAULT_ROLE_ID" "$VAULT_SECRET_ID" || true
  elif [ -f /etc/vault/approle_pg-role.json ]; then
    if command -v jq >/dev/null 2>&1; then
      role_id=$(jq -r '.role_id' /etc/vault/approle_pg-role.json)
      secret_id=$(jq -r '.secret_id' /etc/vault/approle_pg-role.json)
      login_with_approle "$role_id" "$secret_id" || true
    fi
  fi

  if verify_vault_connection 2>/dev/null; then
    echo "Vault reachable, fetching secrets..."
    FETCHED_ADMIN_PASS=$(fetch_secret_field "pg/postgres" "postgres_password" 2>/dev/null) || true
    if [ -n "$FETCHED_ADMIN_PASS" ]; then
      DB_ADMIN_PASSWORD="$FETCHED_ADMIN_PASS"
      echo "Successfully fetched db-admin-password from Vault"
    fi

    FETCHED_REPL_PASS=$(fetch_secret_field "pg/replication" "replication_password" 2>/dev/null) || true
    if [ -n "$FETCHED_REPL_PASS" ]; then
      DB_REPLICATION_PASSWORD="$FETCHED_REPL_PASS"
      echo "Successfully fetched db-replication-password from Vault"
    fi
  else
    echo "Vault not reachable, using environment passwords"
  fi
else
  echo "Vault helper not present, using environment passwords"
fi

# Validate that passwords are set
if [ -z "$DB_ADMIN_PASSWORD" ]; then
  echo "ERROR: DB_ADMIN_PASSWORD not set and could not be fetched from Vault" >&2
  exit 1
fi

if [ -z "$DB_REPLICATION_PASSWORD" ]; then
  echo "ERROR: DB_REPLICATION_PASSWORD not set and could not be fetched from Vault" >&2
  exit 1
fi

# ============================================================================
# SECTION 2: Generate PgBouncer Configuration
# ============================================================================

echo "=== Generating PgBouncer configuration ==="

# Generate userlist.txt dynamically with fetched credentials
echo "Generating userlist.txt with fetched credentials..."
cat > "$PGBOUNCER_CONFIG_DIR/userlist.txt" <<EOF
;; PgBouncer User List - Generated by entrypoint-pgbouncer.sh
;; DO NOT EDIT - Changes will be overwritten on container restart
;; Credentials sourced from Vault secrets management
;;
;; Format: "username" "password"
;; Passwords can be plain text, MD5 ("md5" prefix), or SCRAM-SHA-256

"${DB_ADMIN_USER}" "${DB_ADMIN_PASSWORD}"
"postgres" "${DB_ADMIN_PASSWORD}"
"${DB_REPLICATION_USER}" "${DB_REPLICATION_PASSWORD}"
EOF

# Set permissions
chown postgres:postgres "$PGBOUNCER_CONFIG_DIR/userlist.txt"
chmod 640 "$PGBOUNCER_CONFIG_DIR/userlist.txt"

echo "PgBouncer userlist.txt generated successfully"

# Check if pgbouncer.ini exists, if not create a default
if [ ! -f "$PGBOUNCER_CONFIG_DIR/pgbouncer.ini" ]; then
  echo "PgBouncer configuration not found, generating default..."
  cat > "$PGBOUNCER_CONFIG_DIR/pgbouncer.ini" <<'PGBOUNCER_CONFIG'
;; PgBouncer Configuration File for HA PostgreSQL Cluster
;; Connection pooling for Patroni-managed cluster

[databases]
postgres = host=pg-node-1,pg-node-2,pg-node-3 port=5432 dbname=postgres
pgadmin = host=pg-node-1,pg-node-2,pg-node-3 port=5432 dbname=postgres

[pgbouncer]
; Connection pooling settings
pool_mode = transaction
max_client_conn = 1000
default_pool_size = 25
min_pool_size = 5
reserve_pool_size = 5
reserve_pool_timeout = 30

; Automatic pool recovery
server_lifetime = 3600
server_idle_timeout = 600
server_connect_timeout = 15

; Connection validation
query_wait_timeout = 120
client_idle_timeout = 900

; Logging
log_connections = 1
log_disconnections = 1
log_pooler_errors = 1
log_stats = 1
stats_period = 60

; Admin console
admin_users = pgadmin
stats_users = pgadmin

; Network and authentication
listen_addr = 0.0.0.0
listen_port = 6432
; Disable unix socket for container environment
unix_socket_dir = 
unix_socket_mode = 0777
unix_socket_group = postgres

; Authentication
auth_type = scram-sha-256
auth_file = /etc/pgbouncer/userlist.txt

; Protocol settings
server_round_robin = 1
PGBOUNCER_CONFIG

  chown postgres:postgres "$PGBOUNCER_CONFIG_DIR/pgbouncer.ini"
  chmod 640 "$PGBOUNCER_CONFIG_DIR/pgbouncer.ini"
  echo "Default PgBouncer configuration created"
fi

# ============================================================================
# SECTION 3: Start PgBouncer
# ============================================================================

echo "=== Starting PgBouncer service ==="
echo "Configuration directory: $PGBOUNCER_CONFIG_DIR"
echo "Log directory: $PGBOUNCER_LOG_DIR"
echo "Listen port: $PGBOUNCER_PORT"

# Verify configuration
echo "Verifying PgBouncer configuration..."
if ! pgbouncer -R "$PGBOUNCER_CONFIG_DIR/pgbouncer.ini" --check > /dev/null 2>&1; then
  echo "WARNING: Configuration verification produced warnings, continuing anyway..."
fi

# Start PgBouncer in foreground
echo "Starting PgBouncer..."
exec pgbouncer -u postgres "$PGBOUNCER_CONFIG_DIR/pgbouncer.ini"
