#!/bin/bash
set -e

# ============================================================================
# PgBouncer Entrypoint with Infisical Integration
# ============================================================================

echo "=== Starting PgBouncer with Infisical Integration ==="

# Configuration defaults
PGBOUNCER_CONFIG_DIR="${PGBOUNCER_CONFIG_DIR:-/etc/pgbouncer}"
PGBOUNCER_LOG_DIR="${PGBOUNCER_LOG_DIR:-/var/log/pgbouncer}"
PGBOUNCER_PORT="${PGBOUNCER_PORT:-6432}"

# Create necessary directories
mkdir -p "$PGBOUNCER_CONFIG_DIR" "$PGBOUNCER_LOG_DIR"
chown -R postgres:postgres "$PGBOUNCER_CONFIG_DIR" "$PGBOUNCER_LOG_DIR"
chmod 750 "$PGBOUNCER_CONFIG_DIR"

# ============================================================================
# SECTION 1: Infisical Secrets Integration
# ============================================================================

echo "=== Fetching credentials from Infisical ==="

# Set defaults from environment (fallback if Infisical fails)
DB_ADMIN_USER="${DB_ADMIN_USER:-pgadmin}"
DB_ADMIN_PASSWORD="${DB_ADMIN_PASSWORD}"
DB_REPLICATION_USER="${DB_REPLICATION_USER:-replicator}"
DB_REPLICATION_PASSWORD="${DB_REPLICATION_PASSWORD}"

# Define helper function for fetching secrets (simplified version)
fetch_secret_from_infisical() {
  local secret_key=$1
  local api_key="${INFISICAL_API_KEY}"
  local project_id="${INFISICAL_PROJECT_ID}"
  local environment="${INFISICAL_ENVIRONMENT:-dev}"
  local host="${INFISICAL_HOST:-http://infisical:8020}"
  
  if [ -z "$api_key" ] || [ -z "$project_id" ]; then
    echo "Infisical credentials not set, skipping secret fetch" >&2
    return 1
  fi
  
  curl -s -X GET \
    "${host}/api/v1/secrets/${secret_key}" \
    -H "Authorization: Bearer ${api_key}" \
    -H "X-Infisical-Project-ID: ${project_id}" \
    -H "X-Infisical-Environment: ${environment}" \
    2>/dev/null | grep -o '"value":"[^"]*' | cut -d'"' -f4
}

# Attempt to fetch secrets from Infisical
if [ -n "$INFISICAL_API_KEY" ] && [ -n "$INFISICAL_PROJECT_ID" ]; then
  echo "Infisical integration enabled, fetching secrets..."
  
  # Fetch admin password
  FETCHED_ADMIN_PASS=$(fetch_secret_from_infisical "db-admin-password" 2>/dev/null) || {
    echo "WARNING: Could not fetch db-admin-password from Infisical"
  }
  if [ -n "$FETCHED_ADMIN_PASS" ]; then
    DB_ADMIN_PASSWORD="$FETCHED_ADMIN_PASS"
    echo "Successfully fetched db-admin-password from Infisical"
  fi
  
  # Fetch replication password
  FETCHED_REPL_PASS=$(fetch_secret_from_infisical "db-replication-password" 2>/dev/null) || {
    echo "WARNING: Could not fetch db-replication-password from Infisical"
  }
  if [ -n "$FETCHED_REPL_PASS" ]; then
    DB_REPLICATION_PASSWORD="$FETCHED_REPL_PASS"
    echo "Successfully fetched db-replication-password from Infisical"
  fi
else
  echo "Infisical not configured, using environment passwords"
fi

# Validate that passwords are set
if [ -z "$DB_ADMIN_PASSWORD" ]; then
  echo "ERROR: DB_ADMIN_PASSWORD not set and could not be fetched from Infisical" >&2
  exit 1
fi

if [ -z "$DB_REPLICATION_PASSWORD" ]; then
  echo "ERROR: DB_REPLICATION_PASSWORD not set and could not be fetched from Infisical" >&2
  exit 1
fi

# ============================================================================
# SECTION 2: Generate PgBouncer Configuration
# ============================================================================

echo "=== Generating PgBouncer configuration ==="

# Generate userlist.txt dynamically with fetched credentials
echo "Generating userlist.txt with fetched credentials..."
cat > "$PGBOUNCER_CONFIG_DIR/userlist.txt" <<EOF
;; PgBouncer User List - Generated by entrypoint-pgbouncer.sh
;; DO NOT EDIT - Changes will be overwritten on container restart
;; Credentials sourced from Infisical secrets management
;;
;; Format: "username" "password"
;; Passwords can be plain text, MD5 ("md5" prefix), or SCRAM-SHA-256

"${DB_ADMIN_USER}" "${DB_ADMIN_PASSWORD}"
"${DB_REPLICATION_USER}" "${DB_REPLICATION_PASSWORD}"
EOF

# Set permissions
chown postgres:postgres "$PGBOUNCER_CONFIG_DIR/userlist.txt"
chmod 640 "$PGBOUNCER_CONFIG_DIR/userlist.txt"

echo "PgBouncer userlist.txt generated successfully"

# Check if pgbouncer.ini exists, if not create a default
if [ ! -f "$PGBOUNCER_CONFIG_DIR/pgbouncer.ini" ]; then
  echo "PgBouncer configuration not found, generating default..."
  cat > "$PGBOUNCER_CONFIG_DIR/pgbouncer.ini" <<'PGBOUNCER_CONFIG'
;; PgBouncer Configuration File for HA PostgreSQL Cluster
;; Connection pooling for Patroni-managed cluster

[databases]
postgres = host=pg-node-1,pg-node-2,pg-node-3 port=5432 dbname=postgres
pgadmin = host=pg-node-1,pg-node-2,pg-node-3 port=5432 dbname=postgres

[pgbouncer]
; Connection pooling settings
pool_mode = transaction
max_client_conn = 1000
default_pool_size = 25
min_pool_size = 5
reserve_pool_size = 5
reserve_pool_timeout = 30

; Automatic pool recovery
server_lifetime = 3600
server_idle_timeout = 600
server_connect_timeout = 15

; Connection validation
query_wait_timeout = 120
client_idle_timeout = 900

; Logging
log_connections = 1
log_disconnections = 1
log_pooler_errors = 1
log_stats = 1
stats_period = 60

; Admin console
admin_users = pgadmin
stats_users = pgadmin

; Network and authentication
listen_addr = 0.0.0.0
listen_port = 6432
unix_socket_dir = /var/run/postgresql
unix_socket_mode = 0777
unix_socket_group = postgres

; Authentication
auth_type = scram-sha-256
auth_file = /etc/pgbouncer/userlist.txt

; Protocol settings
server_round_robin = 1
PGBOUNCER_CONFIG

  chown postgres:postgres "$PGBOUNCER_CONFIG_DIR/pgbouncer.ini"
  chmod 640 "$PGBOUNCER_CONFIG_DIR/pgbouncer.ini"
  echo "Default PgBouncer configuration created"
fi

# ============================================================================
# SECTION 3: Start PgBouncer
# ============================================================================

echo "=== Starting PgBouncer service ==="
echo "Configuration directory: $PGBOUNCER_CONFIG_DIR"
echo "Log directory: $PGBOUNCER_LOG_DIR"
echo "Listen port: $PGBOUNCER_PORT"

# Verify configuration
echo "Verifying PgBouncer configuration..."
if ! pgbouncer -R "$PGBOUNCER_CONFIG_DIR/pgbouncer.ini" --check > /dev/null 2>&1; then
  echo "WARNING: Configuration verification produced warnings, continuing anyway..."
fi

# Start PgBouncer in foreground
echo "Starting PgBouncer..."
exec pgbouncer -u postgres "$PGBOUNCER_CONFIG_DIR/pgbouncer.ini"
