#!/bin/bash
set -e

# Add PostgreSQL binaries to PATH
export PATH="/usr/lib/postgresql/18/bin:$PATH"

# Wait for etcd to be ready
echo "Waiting for etcd to be ready..."
until curl -s http://etcd:2379/version > /dev/null 2>&1; do
  echo "etcd is unavailable - sleeping"
  sleep 2
done
echo "etcd is ready"

# Set up PostgreSQL directories with proper permissions
mkdir -p /var/lib/postgresql/18/main
mkdir -p /var/run/postgresql
chown -R postgres:postgres /var/lib/postgresql /var/run/postgresql
chmod 700 /var/lib/postgresql/18/main
chmod 755 /var/lib/postgresql
chmod 755 /var/lib/postgresql/18
chmod 777 /var/run/postgresql 2>/dev/null || true

# Create an initdb wrapper that ensures pg_hba.conf is created with proper entries
# Backup original initdb and replace with wrapper
if [ ! -f /usr/lib/postgresql/18/bin/initdb.real ]; then
  mv /usr/lib/postgresql/18/bin/initdb /usr/lib/postgresql/18/bin/initdb.real
  
  cat > /usr/lib/postgresql/18/bin/initdb <<'INITDB_WRAPPER'
#!/bin/bash
# Wrapper script: call real initdb, then fix pg_hba.conf

# Find the -D parameter to get the data directory
D_PATH=""
ARGS=()
while [[ $# -gt 0 ]]; do
  case $1 in
    -D)
      D_PATH="$2"
      ARGS+=("$1" "$2")
      shift 2
      ;;
    --pgdata=*)
      D_PATH="${1#*=}"
      ARGS+=("$1")
      shift
      ;;
    *)
      ARGS+=("$1")
      shift
      ;;
  esac
done

# Call real initdb
/usr/lib/postgresql/18/bin/initdb.real "${ARGS[@]}"

# Now fix pg_hba.conf
if [ -n "$D_PATH" ] && [ -d "$D_PATH" ]; then
  echo "initdb wrapper: Creating pg_hba.conf entries..."
  cat > "$D_PATH/pg_hba.conf" <<'EOF'
# PostgreSQL Client Authentication Configuration
# Auto-generated by initdb wrapper - Patroni managed
local   all             all                                     trust
host    all             all             127.0.0.1/32            trust
host    all             all             ::1/128                 trust
host    replication     all             172.20.0.0/16           trust
host    all             all             172.20.0.0/16           trust
local   replication     all                                     trust
host    replication     all             127.0.0.1/32            trust
host    replication     all             ::1/128                 trust
EOF
  chmod 600 "$D_PATH/pg_hba.conf"
fi
INITDB_WRAPPER
  
  chmod +x /usr/lib/postgresql/18/bin/initdb
fi

# Initialize pgbackrest if not already done
if [ ! -f /etc/pgbackrest/.initialized ]; then
  echo "Initializing pgbackrest..."
  mkdir -p /etc/pgbackrest
  mkdir -p /var/lib/pgbackrest
  chown -R postgres:postgres /var/lib/pgbackrest
  mkdir -p /var/log/pgbackrest
  chown -R postgres:postgres /var/log/pgbackrest
  touch /etc/pgbackrest/.initialized
fi

# Final permission fix before starting Patroni - ensure all pg directories are correct
echo "Enforcing PostgreSQL directory permissions..."
mkdir -p /var/lib/postgresql/18/main
mkdir -p /var/run/postgresql
chown -R postgres:postgres /var/lib/postgresql /var/run/postgresql
chmod -R 700 /var/lib/postgresql/18/main
chmod 755 /var/lib/postgresql
chmod 755 /var/lib/postgresql/18
chmod 777 /var/run/postgresql 2>/dev/null || true

# Execute Patroni as postgres user with PATH preserved
exec sudo -u postgres env PATH="$PATH" "$@"