resource "null_resource" "vault_init" {
  count      = var.vault_enabled ? 1 : 0
  depends_on = [docker_container.vault]

  provisioner "local-exec" {
    command = "bash ${path.module}/vault-bootstrap.sh ${var.vault_port} pg-role ${var.postgres_user} ${local.postgres_password} ${local.replication_password}"
    environment = {
      # VAULT_ADDR is set here for the host-side curl calls in vault-bootstrap.sh.
      # VAULT_TOKEN is NOT pre-set — the script initialises Vault and obtains the
      # root token dynamically from vault operator init on first run.
      VAULT_ADDR = "http://localhost:${var.vault_port}"
    }
  }

  triggers = {
    vault_enabled = tostring(var.vault_enabled)
    # Changing passwords or the pg user forces a re-seed of KV secrets
    seed = "${var.postgres_user}:${var.password_length}:${var.generate_new_passwords}"
    # Re-run whenever the vault-data volume is recreated (e.g. after terraform destroy + apply)
    vault_volume_id = docker_volume.vault_data[0].id
  }
}

# Destroy-time cleanup: remove the host-side Vault bootstrap secrets
# (.vault-bootstrap/vault-init.json holds the root token + unseal keys, the
# approle/role_id/secret_id files hold AppRole creds). After destroy the
# vault-data volume is gone, so these credentials are dead — leaving them on
# disk is both stale and a security-hygiene problem. They are regenerated by
# vault-bootstrap.sh on the next apply.
resource "null_resource" "vault_bootstrap_cleanup" {
  count = var.vault_enabled ? 1 : 0

  triggers = {
    bootstrap_dir = "${path.module}/.vault-bootstrap"
  }

  provisioner "local-exec" {
    when    = destroy
    command = "rm -f '${self.triggers.bootstrap_dir}/vault-init.json' '${self.triggers.bootstrap_dir}/approle_'*.json '${self.triggers.bootstrap_dir}/role_id' '${self.triggers.bootstrap_dir}/secret_id'"
  }
}

resource "null_resource" "vault_seed" {
  count      = var.vault_enabled ? 1 : 0
  depends_on = [null_resource.vault_init]

  provisioner "local-exec" {
    command = "echo 'Vault seed completed'"
  }

  triggers = {
    seed = "${var.postgres_user}:${var.password_length}:${var.generate_new_passwords}"
  }
}
