#!/bin/bash
# ============================================================================
# setup-airflow-db.sh
# Creates airflow_user and airflow database on the Patroni primary via
# docker exec + psql. Called from null_resource.airflow_db_setup (local-exec).
#
# Env vars required (set by Terraform):
#   AIRFLOW_DB_PASSWORD — password for the airflow_user PostgreSQL role
#   POSTGRES_PASSWORD   — postgres superuser password (for authentication)
#
# Passwords generated by Terraform use override_special = "-_", so only
# [A-Za-z0-9-_] — safe to embed directly in SQL strings.
# ============================================================================
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
# All log functions write to stderr so they don't pollute command-substitution captures
log_info()  { echo -e "${GREEN}[AIRFLOW-DB]${NC} $1" >&2; }
log_warn()  { echo -e "${YELLOW}[AIRFLOW-DB]${NC} $1" >&2; }
log_error() { echo -e "${RED}[AIRFLOW-DB]${NC} $1" >&2; }

MAX_RETRIES="${MAX_RETRIES:-60}"
RETRY_INTERVAL="${RETRY_INTERVAL:-5}"

# This script runs on the HOST via Terraform local-exec.
# Patroni REST API is exposed on host ports 8008/8009/8010.
# docker exec uses the local Docker socket.
declare -A NODE_API_PORTS=(["pg-node-1"]="8008" ["pg-node-2"]="8009" ["pg-node-3"]="8010")

# ---------------------------------------------------------------------------
# discover_primary — return the Docker container name of the Patroni leader
# ---------------------------------------------------------------------------
discover_primary() {
  log_info "Discovering Patroni primary via localhost:8008/8009/8010..."
  local attempt=1
  while [ $attempt -le "$MAX_RETRIES" ]; do
    for node in "pg-node-1" "pg-node-2" "pg-node-3"; do
      port="${NODE_API_PORTS[$node]}"
      http_code=$(curl -s -o /dev/null -w "%{http_code}" \
        "http://localhost:${port}/leader" 2>/dev/null || echo "000")
      if [ "$http_code" = "200" ]; then
        log_info "Primary found: $node (port $port)"
        printf '%s' "$node"
        return 0
      fi
    done
    log_warn "Attempt ${attempt}/${MAX_RETRIES}: no primary yet, retrying in ${RETRY_INTERVAL}s..."
    sleep "$RETRY_INTERVAL"
    ((attempt++))
  done
  log_error "No Patroni primary found after $((MAX_RETRIES * RETRY_INTERVAL))s"
  return 1
}

PRIMARY=$(discover_primary)
log_info "Using primary node: $PRIMARY"

# ---------------------------------------------------------------------------
# Create airflow_user role (idempotent: create or update password)
# PGPASSWORD is passed via -e into the container for psql authentication.
# The password values are expanded by the HOST shell in the heredoc,
# which is safe because Terraform's override_special="-_" produces
# alphanumeric + hyphen/underscore only.
# ---------------------------------------------------------------------------
log_info "Creating/updating airflow_user role..."
docker exec -i \
  -e "PGPASSWORD=${POSTGRES_PASSWORD}" \
  "$PRIMARY" \
  psql -U postgres -d postgres <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'airflow_user') THEN
    CREATE ROLE airflow_user WITH LOGIN PASSWORD '${AIRFLOW_DB_PASSWORD}';
    RAISE NOTICE 'airflow_user created';
  ELSE
    ALTER ROLE airflow_user WITH PASSWORD '${AIRFLOW_DB_PASSWORD}';
    RAISE NOTICE 'airflow_user password updated';
  END IF;
END \$\$;
SQL

# ---------------------------------------------------------------------------
# Create airflow database (idempotent: skip if already exists)
# ---------------------------------------------------------------------------
log_info "Creating airflow database..."
docker exec -i \
  -e "PGPASSWORD=${POSTGRES_PASSWORD}" \
  "$PRIMARY" \
  psql -U postgres -d postgres <<'SQL'
SELECT 'CREATE DATABASE airflow OWNER airflow_user'
WHERE NOT EXISTS (SELECT FROM pg_catalog.pg_database WHERE datname = 'airflow')\gexec
SQL

# ---------------------------------------------------------------------------
# Grant privileges
# ---------------------------------------------------------------------------
log_info "Granting privileges..."
docker exec -i \
  -e "PGPASSWORD=${POSTGRES_PASSWORD}" \
  "$PRIMARY" \
  psql -U postgres -d postgres <<'SQL'
GRANT ALL PRIVILEGES ON DATABASE airflow TO airflow_user;
GRANT CONNECT ON DATABASE airflow TO airflow_user;
SQL

log_info "Airflow DB setup complete on $PRIMARY: airflow_user + airflow database ready"
